#!/bin/bash

set -e

container=$(basename $(readlink -f $0))
cmd=$(basename $0)
root=$(readlink -f $(dirname $0))
work=$(echo $PWD | sed -e s,$root/,,g)
mnt=/${container}.demesne

#echo "container = $container"
#echo "cmd       = $cmd"
#echo "root      = $root"
#echo "work      = $work"
#exit 0

if [[ "$work" == ..* ]] || [[ "$work" == /* ]]; then
  work=""
fi

volumes=(-v $root:$mnt)

function docker_rm {
  echo --rm=$( [ "$CIRCLECI" == "true" ] && echo false || echo true )
}

function build {
  docker build -t $container $(docker_rm) $root
}

function get_label {
  label=$1
  docker inspect --format="{{ index .Config.Labels \"demesne.${label}\"}}" $container
}

function docker_exec {
  env=()
  preserve=()
  for e in ${preserve[@]}; do
    if [ "${!e}" != "" ]; then
      env+=(-e $e=${!e})
    fi
  done
  if [ "$CIRCLECI" == "true" ]; then
    exec docker run \
      $(docker_rm) \
      ${env[@]} \
      ${volumes[@]} \
      -w $mnt \
      --entrypoint /bin/bash \
      $container \
      -c "\$@" -- $@
  else
    exec docker exec ${env[@]} -it $container bash -c "cd $mnt/$work; exec /usr/bin/env PS1='\\w \\$ ' \$@" -- "$@"
  fi
}

function clean_up {
  docker stop $container || true
  docker rm -f $container || true
}

if [ "$CIRCLECI" == "true" ] || [ "$(docker images -q $container)" == "" ]; then
  build
else
  dockerfile_time=$(stat -c %Y $root/Dockerfile $0 | sort -nr | head -1)
  build_time=$(get_label 'build_time')
  if [ ${build_time:-$(date +%s)} -lt $dockerfile_time ]; then
    clean_up
    build
  fi
fi

if [ "$(docker ps -qa -f name=$container)" == "" ] && [ "$CIRCLECI" != "true" ]; then
  volumes+=(-v $HOME/.aws:/root/.aws)
  docker run \
    -h $container \
    -P \
    ${volumes[@]} \
    -w $mnt \
    -td \
    --name $container \
    --entrypoint /bin/bash \
    --label demesne.build_time=$(date +%s) \
    $container \
    >/dev/null
fi

if [ "$(docker ps -qa -f name=$container -f status=running)" == "" ] && [ "$CIRCLECI" != "true" ]; then
  docker start $container >/dev/null
fi

if [ "$cmd" == ".shell" ]; then
  docker_exec /bin/bash
elif [ "$cmd" == "$container" ]; then
  docker_exec "$container $@"
else
  docker_exec "$cmd $@"
fi
