# -*- mode: dockerfile -*-
# vi: set ft=dockerfile :

FROM demesne

ENV TERRAFORM_VERSION 0.9.8
ENV TERRAFORM_ZIPBALL https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

RUN curl -sL -o terraform.zip $TERRAFORM_ZIPBALL && \
    sudo apt-get install -y zip && \
    unzip terraform.zip && \
    sudo install -m 0755 -p terraform /usr/local/bin/ && \
    rm -f terraform terraform.zip
ENTRYPOINT ["/bin/bash"]
