# -*- mode: dockerfile -*-
# vi: set ft=dockerfile :

FROM demesne

RUN curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash - \
    && sudo apt-get install -y nodejs

RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - \
    && sudo add-apt-repository "deb https://dl.yarnpkg.com/debian/ stable main" \
    && sudo apt-get update \
    && sudo apt-get install -y yarn build-essential \
    && sudo yarn global add npm

ENTRYPOINT ["/bin/bash"]
