#!/bin/bash

root=$(readlink -f $(dirname $0))

name=""
cmds=()
volumes=()
env=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--name)
      name="$2"
      shift
      ;;
    -v|--volume)
      volumes+=("$2")
      shift
      ;;
    -e|--env)
      env+=("$2")
      shift
      ;;
    *)
      cmds+=("$1")
      ;;
  esac
  shift
done

dir=$root/${name}.demesne
mkdir -pv $dir
ln -vf $root/demesne $dir/$name
ln -svf $dir/$name $dir/${name}-shell
ln -vf $root/Dockerfile $dir/Dockerfile.base
dockerfile=$root/Dockerfile.${name}
[ -f $dockerfile ] || dockerfile=$root/Dockerfile
cp -v $dockerfile $dir/Dockerfile
cp -v $root/.dockerignore $dir

for cmd in ${cmds[@]}; do
  if [ "$name" != "$cmd" ]; then
    ln -svf $dir/$name $dir/$cmd
  fi
done

for volume in ${volumes[@]}; do
  [ -d $volume ] || [ -f $volume ] || [ -L $volume ] || mkdir -p $volume
  echo $volume | sed -e s,^"$HOME",~,g
done >$dir/.volumes

for env in ${env[@]}; do
  echo $env
done >$dir/.env
