#!/bin/bash

root=$(readlink -f $(dirname $0))

name=""
cmds=()

while [[ $# -gt 1 ]]; do
  case "$1" in
    -n|--name)
      name="$2"
      shift
      ;;
    *)
      cmds+=("$2")
      shift
      ;;
  esac
done

dir=$root/${name}.demesne
mkdir -pv $dir
ln -vf $root/demesne $dir/$name
ln -svf $dir/$name $dir/${name}-shell
ln -vf $root/Dockerfile $dir/Dockerfile.base
dockerfile=$root/Dockerfile.${name}
[ -f $dockerfile ] || dockerfile=$root/Dockerfile
cp -v $dockerfile $dir/Dockerfile
cp -v $root/.dockerignore $dir

for cmd in ${cmds[@]}; do
  ln -svf $dir/$name $dir/$cmd
done
