#!/bin/bash

root=$(readlink -f $(dirname $0))

name=""
cmds=()
volumes=()
env=()
links=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -n|--name)
      name="$2"
      shift
      ;;
    -v|--volume)
      volumes+=("$2")
      shift
      ;;
    -e|--env)
      env+=("$2")
      shift
      ;;
    -l|--link)
      links+=("$2")
      shift
      ;;
    *)
      cmds+=("$1")
      ;;
  esac
  shift
done

dir=$root/${name}.demesne
mkdir -pv $dir
ln -vf $root/demesne $dir/$name
ln -svf $name $dir/${name}-shell
ln -vf $root/Dockerfile $dir/Dockerfile.base
dockerfile=$root/Dockerfile.${name}
[ -f $dockerfile ] || dockerfile=$root/Dockerfile
cp -v $dockerfile $dir/Dockerfile
cp -v $root/.dockerignore $dir
bash_env=$root/.bash_env.$name
[ -f $bash_env ] && cp -v $bash_env $dir/.bash_env || touch $dir/.bash_env

echo $name >$dir/.cmds
for cmd in ${cmds[@]}; do
  if [ "$name" != "$cmd" ]; then
    ln -svf $name $dir/$cmd
  fi
  echo $cmd >>$dir/.cmds
done

(
  for volume in ${volumes[@]}; do
    [ -d $volume ] || [ -f $volume ] || [ -L $volume ] || mkdir -p $volume 2>/dev/null || true
    echo $volume | sed -e s,^"$HOME",~,g
  done
  echo "$(readlink -f /var/run/docker.sock)"
) >$dir/.volumes

for env in ${env[@]}; do
  echo $env
done >$dir/.env

>$dir/.links
for link in ${links[@]}; do
  echo $link >>$dir/.links
done
