#!/bin/bash

path=$PATH
root=$(dirname $(readlink -f $0))

for dir in $(find \
  $root \
  -mindepth 1 -maxdepth 1 \
  -type d -name '*.demesne'); do
  path="$dir:$path"
done

var="PATH=\"$root:$path\""

if [ ${#@} -gt 0 ]; then
  exec env "$var" $@
else
  echo "$var"
fi
